import "mapbox-gl/dist/mapbox-gl.css";
import "@radix-ui/themes/styles.css";
import "../styles/index.scss";

import { Analytics } from "@vercel/analytics/react";
import localFont from 'next/font/local'
import { Theme } from "@radix-ui/themes";
import ClientTheme from "./clientTheme";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

const mona =  localFont({
 src: './../../public/Mona-Sans.woff2',
  display: 'swap',
  variable: '--font-mona-sans'
})

const hubot =  localFont({
  src: './../../public/Hubot-Sans.woff2',
   display: 'swap',
   variable: '--font-hubot-sans'
 })

export default function Layout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning className={`${mona.variable} ${hubot.variable}`}>
			<body>
				<ClientTheme>
					<Theme
						panelBackground="translucent"
						accentColor="iris"
						grayColor="slate"
						radius="medium"
						scaling="95%"
					>
						{children}
					</Theme>
				</ClientTheme>
			</body>
			<Analytics />
		</html>
	);
}
