import "../styles/index.scss";
import "../styles/App.css";
import "mapbox-gl/dist/mapbox-gl.css";
import "@radix-ui/themes/styles.css";

import { Analytics } from "@vercel/analytics/react";
import { Providers } from "./providers";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function Layout({ children }) {
	return (
		<html suppressHydrationWarning>
			<head />
			<body>
				<Providers>{children}</Providers>
			</body>
			<Analytics />
		</html>
	);
}
